### ISSUE TITLE
PR title check returns same result after PR title is changed.

### ISSUE THREAD

**Issue by lobeto99** [ryanvade/enforce-pr-title-style-action#12]
The action always returns the result of the first execution even after the title has changed. If the check fails for an invalid title and the title is updated to a valid title, the action will still fail and vice versa.
The code looks sound so I'm wondering if this is a shortcoming in the github API when `github.context.payload.pull_request` is called?

**Comment by ilorsh-tr** [comment]
I'm facing this problem too.

**Comment by jdonboch** [comment]
I'm seeing this as well
