### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by kamesh-09** [ryanvade/enforce-pr-title-style-action#86]
Using the latest version is throwing below error:

![image (4)](https://github.com/ryanvade/enforce-pr-title-style-action/assets/140370022/8be46a7b-fb5f-49a7-9f59-88e3607743d7)

I am using below version in my yml file: the latest one

uses: ryanvade/enforce-pr-title-style-action@v2.1

Going through same issues here - https://github.com/Azure/docker-login/issues/3
Mentions to add node_modules.

**Comment by ryanvade** [comment]
This should be fixed with https://github.com/ryanvade/enforce-pr-title-style-action/releases/tag/v2.1.1

Including the `node_modules` directory is not required when using https://github.com/vercel/ncc which I failed to do for the v2.1 release.
